### ISSUE TITLE
Ŭoŭ! (ne "issue")

### ISSUE THREAD

**Issue by Loppansson** [Esperantumo/La-Epoko-de-Fablo#1]
Ĉi tio ne estas "issue", mi nur volas diri ke mi ŝatas viajn videojn, kaj ĉi tiu projekto ŝajnas mojosa:)
Mi esperas ke vi havas bonan tagon <3

**Comment by Esperantumo** [comment]
> Ĉi tio ne estas "issue", mi nur volas diri ke mi ŝatas viajn videojn, kaj ĉi tiu projekto ŝajnas mojosa:)
> 
> Mi esperas ke vi havas bonan tagon <3

Dankon amiko! Mi ĝojas ke vi ĝuas la filmetojn 💚
